language: python
python:
- '3.6'
before_install:
# Decrypt deploy key
- openssl aes-256-cbc -K $encrypted_4260086be8d4_key -iv $encrypted_4260086be8d4_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
- chmod 600 .travis/deploy_key
# Start ssh-agent
- eval "$(ssh-agent -s)"
- ssh-add .travis/deploy_key
- git config --global user.email "pypi-dump@pypi.dump"
- git config --global user.name "pypi-dump"
- git config --global push.default matching
# We're going to push over ssh.
- git remote set-url origin git@github.com:FRidh/pypi-dump.git
install:
- pip install aiohttp
script:
- SCRIPT="https://raw.githubusercontent.com/FRidh/make-pypi-dump/1c158f3dda1848c7020f6c0fd4839e32530db5cc/make-pypi-dump"
- SCRIPTNAME="make-pypi-dump"
- wget $SCRIPT -O $SCRIPTNAME
- chmod +x $SCRIPTNAME
- "./$SCRIPTNAME --update ."
after_success:
- git status
- git add json
- git add state.json
- git commit -m "$(cat state.json | grep timestamp | xargs)"
# Note that $TRAVIS_BRANCH is incorrect for PRs.
- echo $TRAVIS_BRANCH
- git push origin HEAD:$TRAVIS_BRANCH

